### ISSUE TITLE
Provider-sdk: For typescript, lets add type to swagger schema

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#148]
We could use projects such as https://github.com/lbovet/typson/ to implicitly convert typescript types to swagger schemas. 

This way we could simply use types instead of writing explicit jsons.

**Comment by shlomi-nx** [comment]
We could also write something more custom by traversing the AST https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#traversing-the-ast-with-a-little-linter

**Comment by joshua-berry-ntnx** [comment]
Either this or #348 should probably be closed as a dup of the other (since both wind up in the same place--Swagger types and TypeScript types are in agreement).

IMO it will be much easier to go the other direction--infer a TypeScript type from the Swagger schema, so long as the Swagger schema is provided as a TypeScript expression at compile time (not loaded dynamically from YAML). Admittedly it's not as nice since you still must write explicit JSON, but the compiler will at least type-check your code at compile time against what is defined in the Swagger JSON.

**Comment by shlomi-nx** [comment]
Closing this as a duplicate of #348. I agree with @joshua-berry-ntnx's direction.
