### ISSUE TITLE
Lets get Key type back

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#242]
I dont know why type `Key` was removed in this commit https://github.com/nutanix/papiea-js/commit/0dd59f84df19e0c2e05a1fc0bb5c2a62b46a7926

It is much more typesafe to designate that this is a `Key` even though its an alias to a string.

Please undo this change, and lets discuss these kinds of changes next time.

**Comment by Emulebest** [comment]
The problems I see with defining `type Key = string`:
1) We have a naming problem with the keys, s2s key is a structure defined as
```javascript
interface S2S_Key {
    name?: string
    owner: string
    provider_prefix: string
    key: string
    uuid: string;

    created_at: Date
    deleted_at?: Date
    userInfo: UserInfo
}
```
while Key is a mere alias to string
```javascript
type Key = string
```
Functions like previously defined `async get_key_by_secret(key: Key): Promise<S2S_Key>` make it very confusing to get a grasp of why need need this function, how it works, what part is a secret and what type is a `Key` and why need this. (I changed it to `async get_key_by_secret(secret: string): Promise<S2S_Key>` however secret is not even a secret per se)

2) Typescript's aliasing doesn't make it typesafe to assign an alias, moreover I think that in case of simple aliasing it even harms the typesafeness because of no runtime type checks.

3) Typescript's aliasing is not offering compile time checks either like https://wiki.haskell.org/Type#Type_and_newtype

4) Typescript's aliasing doesn't give any capabilities for https://en.wikipedia.org/wiki/Refinement_type, thus not giving any sanity checks as well

The only positive thing that I see is having a single definition point for the `Key`, so that if it changes type, we can make a single changes there. However I don't see this part changing to anything else than `string` in the near future. 

My proposition would be to either make a typesafe wrapper around `Key` if we need it (https://github.com/gcanti/newtype-ts) or get rid of confusing `secret` term and leave `Key` type as is.

**Comment by shlomi-nx** [comment]
That only positive thing you saw is precisely what I am after. It allows us to discard the internal representation of a secret when defining the API. We can change `Key` to be any type definition in the future (PKI, string adhering to some rules, uuid, compressed byte array, a container for rest api calls to get and store keys contents from some secure keystore, etc.). This lets us be more flexible than simply sticking with `string`. Hiding the fact that its a string behind a type constructor may be even better.

Regarding the confusing names, we can perhaps think of better names. Maybe `S2S_Key` and `Secret` instead of `Key`.

And regarding your lens proposition, good stuff indeed but I feel as overkill here.

**Comment by Emulebest** [comment]
Let's go with making `Key` a proper class with a constructor and resolving confusing naming, what do you think?

**Comment by shlomi-nx** [comment]
Either a class with an internal constructor, or an interface with constructor functions. I personally like the second, but I don't mind. Here is an example of this approach: https://github.com/nutanix/papiea-js/blob/a9d3245a5925bd5e3babb40d803b14291d1025f7/papiea-client/src/entity_client.ts#L75-L99

However, don't stress it. If you feel more strongly about a class with a constructor go for it.

**Comment by Emulebest** [comment]
Got it, will do
