### ISSUE TITLE
Permissions allow everybody to read a provider

### ISSUE THREAD

**Issue by adolgarev** [nutanix/papiea-js#299]
Everybody can read a provider, please fix this security hole.

**Comment by Emulebest** [comment]
I see 2 methods of approaching this problem:
1) Since papiea uses provider_api in many place (e.g. entity_api), which has `Action.ReadProvider` checks all over the place, we can go through that checks to DB if not working with requests to provider_api directly (internal papiea usage)
2) We can make provider permissions more atomic. Make `Action.ReadProvider` and `Action.DetailProvider` which expose public and private info about provider accordingly. This is a better way IMO but requires more time to implement
