### ISSUE TITLE
Initial performance benchmark

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#365]
We need to start gathering some performance characteristics of Papiea. We need the following:

1. A simple, no-op provider that:
   1. has a three procedures: entity, kind and provider level
   2. has an intentful operation that does nothing but resolve the diff
2. Run it on a typical server machine in AWS
3. Create a client which blasts requests (can run few client instances in parallel)
   1. Measure DB operations only (create, filter, get, delete)
   2. Measure operations involving provider:
       1. Procedure invocations (each)
       2. Intentful invocation (PUT requests):
           1. Each testing client should work with his own entities, so no race conditions
           1. Measure two things: 
               a. Time to succeed setting the operation (CAS)
               b. Time to complete operation (Intentful handler done)
               c. As an extra step, we could have the intentful handler fail every so often to account for retries.

**Comment by shlomi-nx** [comment]
We need to come up with numbers for throughput reqs per sec per node, and latency for:
1. DB operations
2. Procedure operations
3. Intentful operations

Don't worry about the numbers, don't optimize yet. It is clear that we have not yet optimized and there are probably many low-hanging fruits. 

This is just to get a picture of where we are. Based on this we will make focused analysis into hotspots when appropriate.

**Comment by Emulebest** [comment]
Here are the results of running papiea benchmarks on t2.medium instance (2 CPUs, 4 GB RAM):
CRUD:
1. Create Entities - 225 rps :: 43 ms latency
2. Read Entities - 430 rps :: 22 ms latency
3. Update Entities - 187 rps :: 51 ms latency
4. Delete Entities - 275 rps :: 35 ms latency

Procedures:
1. Entity procedure - 148 rps :: 67 ms latency
2. Kind procedure - 280 rps :: 35 ms latency
3. Provider procedure - 413 rps :: 24 ms latency

Intentful Operations:
1. CAS - 520 ms latency (measured with axios http client, not a benchmark framework due to results being used in a later benchmark. Timings might be a bit lower)
2. Intentful Handler Resolution - 1.5 - 3 seconds (this depends on the scheduler timeouts, the benchmark was run on the default values)

**Comment by Emulebest** [comment]
UPD (run with mongo being on another instance): 
NET IO - 56 MB sent and received for a single bench run
BLOCK IO - 158 MB (The amount of data the container has read to and written from block devices on the host)
CPU (peak) - 106 %
